//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace DMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCMNT_TBL
    {
        public DCMNT_TBL()
        {
            DEPT_ID = 0;
        }
        public long DCMT_ID { get; set; }
        [Required(ErrorMessage = "Policy Number is Required")]

        public string PLCY_NUM { get; set; }
        public string SCAN_DTE { get; set; }
        public string FILE_NME { get; set; }
        [Required(ErrorMessage = "First Name is Required")]
        public string FRST_NME { get; set; }
        [Required(ErrorMessage = "Last Name is Required")]
        public string LAST_NME { get; set; }
        public string STRG_LOC { get; set; }
        public string DCMT_NTE { get; set; }
        public Nullable<bool> DCMT_IsChk { get; set; }
        public Nullable<bool> DCMT_IsScan { get; set; }
        public string SCAN_TME { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> DCMT_TYPE_ID { get; set; }
        public Nullable<int> PLCY_ID { get; set; }
        [Required(ErrorMessage = "Plan is not selected")]

        public Nullable<int> PLAN_ID { get; set; }
        [Required(ErrorMessage = "Product Type is not selected")]
        public Nullable<int> PRDCT_TYPE_ID { get; set; }

        public Nullable<int> EXTN_ID { get; set; }
        [Required(ErrorMessage = "Department is not selected")]
        public Nullable<int> DEPT_ID { get; set; }
    }
}
