//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TBL
    {
        public long USER_ID { get; set; }
        public string FRST_NME { get; set; }
        public string LAST_NME { get; set; }
        public Nullable<int> GNDR { get; set; }
        public string DOB { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_Username { get; set; }
        public string USER_Password { get; set; }
        public string USER_Phone { get; set; }
        public string USER_Address { get; set; }
    
        public virtual DEPT_TBL DEPT_TBL { get; set; }
        public virtual ROLE_TBL ROLE_TBL { get; set; }
    }
}
